"""
create_playlist.py
creates a playlist in user librabry and returns the playlist id
parameters: auth, list of tracks to add 
"""
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from .spotifyoauth import get_token
from ..common import session

def create_playlist(name, songs):
    #get token 
    
    session['token_info'], authorized = get_token()
    
    if authorized:
        sp = spotipy.Spotify(auth=session.get('token_info').get('access_token'))
    
        user_id = sp.me()['id']

        playlist_name = name
        playlist_description = "Playlist generated by Spotify Open Recommendation Engine"
    
        #create playlist 
        playlist = sp.user_playlist_create(user_id, playlist_name, public=True, collaborative=False, description = playlist_description ) 
   
        #add tracks to playlist 
        playlist_id = playlist['id']
        sp.user_playlist_add_tracks(user_id, playlist_id = playlist_id, tracks = songs)

        return playlist_id
    else:
        return "(search_for) error: not authorized"
